### ISSUE TITLE
Codes doesnt work for any other image

### ISSUE THREAD

**Issue by khanamrin** [srivatsansoft/Virtual-Makeup#6]
Is the code intended just for da pic taken as example?
Is does not work for any other pic

**Comment by srivatsan-ramesh** [comment]
It will work if you provide the corresponding points file for the pic. The code doesn't find the points by itself. The code is just a demonstration of how color transfer can be done.

**Comment by khanamrin** [comment]
Do you have a reference code to extract the points in real time?
